insert into teams (name, is_active) values ('Violet-eared waxbill', false);
insert into teams (name, is_active) values ('Goat, mountain', true);
insert into teams (name, is_active) values ('Dragon, netted rock', true);
insert into teams (name, is_active) values ('Hanuman langur', false);
insert into teams (name, is_active) values ('Woodpecker, downy', true);
insert into teams (name, is_active) values ('Bunting, crested', false);
insert into teams (name, is_active) values ('Butterfly, tropical buckeye', true);
insert into teams (name, is_active) values ('Sungazer, yellow-brown', true);
insert into teams (name, is_active) values ('Stick insect', false);
insert into teams (name, is_active) values ('Sage hen', true);
insert into teams (name, is_active) values ('Trumpeter swan', false);
insert into teams (name, is_active) values ('Black swan', false);
insert into teams (name, is_active) values ('Cormorant, king', false);
insert into teams (name, is_active) values ('Siskin, yellow-rumped', false);
insert into teams (name, is_active) values ('Cape cobra', true);
insert into teams (name, is_active) values ('Blue peacock', true);
insert into teams (name, is_active) values ('White-cheeked pintail', false);
insert into teams (name, is_active) values ('Albatross, waved', true);
insert into teams (name, is_active) values ('African porcupine', false);
insert into teams (name, is_active) values ('Squirrel glider', false);
insert into teams (name, is_active) values ('Genet, small-spotted', true);
insert into teams (name, is_active) values ('Monkey, rhesus', false);
insert into teams (name, is_active) values ('Indian giant squirrel', true);
insert into teams (name, is_active) values ('Buffalo, african', false);
insert into teams (name, is_active) values ('Anteater, australian spiny', true);
insert into teams (name, is_active) values ('Gelada baboon', false);
insert into teams (name, is_active) values ('Crane, black-crowned', false);
insert into teams (name, is_active) values ('Silver-backed jackal', false);
insert into teams (name, is_active) values ('Grouse, greater sage', false);
insert into teams (name, is_active) values ('Turkey, common', false);
insert into teams (name, is_active) values ('Owl, burrowing', false);
insert into teams (name, is_active) values ('Black kite', false);
insert into teams (name, is_active) values ('Goose, greylag', true);
insert into teams (name, is_active) values ('Black spider monkey', true);
insert into teams (name, is_active) values ('Tern, arctic', false);
insert into teams (name, is_active) values ('Black curlew', false);
insert into teams (name, is_active) values ('Woodchuck', false);
insert into teams (name, is_active) values ('Paddy heron (unidentified)', false);
insert into teams (name, is_active) values ('Burchell''s gonolek', false);
insert into teams (name, is_active) values ('Squirrel glider', false);
insert into teams (name, is_active) values ('Killer whale', false);
insert into teams (name, is_active) values ('Polecat, african', false);
insert into teams (name, is_active) values ('Camel, dromedary', false);
insert into teams (name, is_active) values ('African ground squirrel (unidentified)', true);
insert into teams (name, is_active) values ('Black-collared barbet', false);
insert into teams (name, is_active) values ('Jaguar', false);
insert into teams (name, is_active) values ('Blue shark', false);
insert into teams (name, is_active) values ('European badger', false);
insert into teams (name, is_active) values ('African pied wagtail', false);
insert into teams (name, is_active) values ('Laughing dove', true);
insert into teams (name, is_active) values ('Wild boar', false);
insert into teams (name, is_active) values ('American beaver', false);
insert into teams (name, is_active) values ('Red hartebeest', true);
insert into teams (name, is_active) values ('Steller sea lion', true);
insert into teams (name, is_active) values ('Platypus', true);
insert into teams (name, is_active) values ('Duck, blue', true);
insert into teams (name, is_active) values ('Ibis, sacred', false);
insert into teams (name, is_active) values ('Baboon, yellow', true);
insert into teams (name, is_active) values ('Bee-eater (unidentified)', false);
insert into teams (name, is_active) values ('Constrictor, eastern boa', false);
insert into teams (name, is_active) values ('Barasingha deer', false);
insert into teams (name, is_active) values ('American alligator', true);
insert into teams (name, is_active) values ('Cobra, cape', false);
insert into teams (name, is_active) values ('Gnu, brindled', true);
insert into teams (name, is_active) values ('Wapiti, elk,', false);
insert into teams (name, is_active) values ('Catfish, blue', false);
insert into teams (name, is_active) values ('Paddy heron (unidentified)', true);
insert into teams (name, is_active) values ('Jackal, silver-backed', false);
insert into teams (name, is_active) values ('Civet (unidentified)', true);
insert into teams (name, is_active) values ('Dove, mourning collared', true);
insert into teams (name, is_active) values ('Jackal, indian', false);
insert into teams (name, is_active) values ('Marmot, yellow-bellied', true);
insert into teams (name, is_active) values ('Seven-banded armadillo', true);
insert into teams (name, is_active) values ('Plover, blacksmith', false);
insert into teams (name, is_active) values ('American bison', true);

--rollback truncate table teams;