insert into user_teams (user_id, team_id, is_leader) values (1, 1, true);
insert into user_teams (user_id, team_id, is_leader) values (2, 2, true);
insert into user_teams (user_id, team_id, is_leader) values (3, 3, true);
insert into user_teams (user_id, team_id, is_leader) values (4, 4, true);
insert into user_teams (user_id, team_id, is_leader) values (5, 5, true);
insert into user_teams (user_id, team_id, is_leader) values (6, 6, true);
insert into user_teams (user_id, team_id, is_leader) values (7, 7, true);
insert into user_teams (user_id, team_id, is_leader) values (8, 8, true);
insert into user_teams (user_id, team_id, is_leader) values (9, 9, true);
insert into user_teams (user_id, team_id, is_leader) values (10, 10, true);
insert into user_teams (user_id, team_id, is_leader) values (11, 11, true);
insert into user_teams (user_id, team_id, is_leader) values (12, 12, true);
insert into user_teams (user_id, team_id, is_leader) values (13, 13, true);
insert into user_teams (user_id, team_id, is_leader) values (14, 14, true);
insert into user_teams (user_id, team_id, is_leader) values (15, 15, true);
insert into user_teams (user_id, team_id, is_leader) values (16, 16, true);
insert into user_teams (user_id, team_id, is_leader) values (17, 17, true);
insert into user_teams (user_id, team_id, is_leader) values (18, 18, true);
insert into user_teams (user_id, team_id, is_leader) values (19, 19, true);
insert into user_teams (user_id, team_id, is_leader) values (20, 20, true);
insert into user_teams (user_id, team_id, is_leader) values (21, 21, true);
insert into user_teams (user_id, team_id, is_leader) values (22, 22, true);
insert into user_teams (user_id, team_id, is_leader) values (23, 23, true);
insert into user_teams (user_id, team_id, is_leader) values (24, 24, true);
insert into user_teams (user_id, team_id, is_leader) values (25, 25, true);
insert into user_teams (user_id, team_id, is_leader) values (26, 26, true);
insert into user_teams (user_id, team_id, is_leader) values (27, 27, true);
insert into user_teams (user_id, team_id, is_leader) values (28, 28, true);
insert into user_teams (user_id, team_id, is_leader) values (29, 29, true);
insert into user_teams (user_id, team_id, is_leader) values (30, 30, true);
insert into user_teams (user_id, team_id, is_leader) values (31, 31, true);
insert into user_teams (user_id, team_id, is_leader) values (32, 32, true);
insert into user_teams (user_id, team_id, is_leader) values (33, 33, true);
insert into user_teams (user_id, team_id, is_leader) values (34, 34, true);
insert into user_teams (user_id, team_id, is_leader) values (35, 35, true);
insert into user_teams (user_id, team_id, is_leader) values (36, 36, true);
insert into user_teams (user_id, team_id, is_leader) values (37, 37, true);
insert into user_teams (user_id, team_id, is_leader) values (38, 38, true);
insert into user_teams (user_id, team_id, is_leader) values (39, 39, true);
insert into user_teams (user_id, team_id, is_leader) values (40, 40, true);
insert into user_teams (user_id, team_id, is_leader) values (41, 41, true);
insert into user_teams (user_id, team_id, is_leader) values (42, 42, true);
insert into user_teams (user_id, team_id, is_leader) values (43, 43, true);
insert into user_teams (user_id, team_id, is_leader) values (44, 44, true);
insert into user_teams (user_id, team_id, is_leader) values (45, 45, true);
insert into user_teams (user_id, team_id, is_leader) values (46, 46, true);
insert into user_teams (user_id, team_id, is_leader) values (47, 47, true);
insert into user_teams (user_id, team_id, is_leader) values (48, 48, true);
insert into user_teams (user_id, team_id, is_leader) values (49, 49, true);
insert into user_teams (user_id, team_id, is_leader) values (50, 50, true);
insert into user_teams (user_id, team_id, is_leader) values (51, 51, true);
insert into user_teams (user_id, team_id, is_leader) values (52, 52, true);
insert into user_teams (user_id, team_id, is_leader) values (53, 53, true);
insert into user_teams (user_id, team_id, is_leader) values (54, 54, true);
insert into user_teams (user_id, team_id, is_leader) values (55, 55, true);
insert into user_teams (user_id, team_id, is_leader) values (56, 56, true);
insert into user_teams (user_id, team_id, is_leader) values (57, 57, true);
insert into user_teams (user_id, team_id, is_leader) values (58, 58, true);
insert into user_teams (user_id, team_id, is_leader) values (59, 59, true);
insert into user_teams (user_id, team_id, is_leader) values (60, 60, true);
insert into user_teams (user_id, team_id, is_leader) values (61, 61, true);
insert into user_teams (user_id, team_id, is_leader) values (62, 62, true);
insert into user_teams (user_id, team_id, is_leader) values (63, 63, true);
insert into user_teams (user_id, team_id, is_leader) values (64, 64, true);
insert into user_teams (user_id, team_id, is_leader) values (65, 65, true);
insert into user_teams (user_id, team_id, is_leader) values (66, 66, true);
insert into user_teams (user_id, team_id, is_leader) values (67, 67, true);
insert into user_teams (user_id, team_id, is_leader) values (68, 68, true);
insert into user_teams (user_id, team_id, is_leader) values (69, 69, true);
insert into user_teams (user_id, team_id, is_leader) values (70, 70, true);
insert into user_teams (user_id, team_id, is_leader) values (71, 71, true);
insert into user_teams (user_id, team_id, is_leader) values (72, 72, true);
insert into user_teams (user_id, team_id, is_leader) values (73, 73, true);
insert into user_teams (user_id, team_id, is_leader) values (74, 74, true);
insert into user_teams (user_id, team_id, is_leader) values (75, 75, true);
insert into user_teams (user_id, team_id) values (76, 1);
insert into user_teams (user_id, team_id) values (77, 2);
insert into user_teams (user_id, team_id) values (78, 3);
insert into user_teams (user_id, team_id) values (79, 4);
insert into user_teams (user_id, team_id) values (80, 5);
insert into user_teams (user_id, team_id) values (81, 6);
insert into user_teams (user_id, team_id) values (82, 7);
insert into user_teams (user_id, team_id) values (83, 8);
insert into user_teams (user_id, team_id) values (84, 9);
insert into user_teams (user_id, team_id) values (85, 10);
insert into user_teams (user_id, team_id) values (86, 11);
insert into user_teams (user_id, team_id) values (87, 12);
insert into user_teams (user_id, team_id) values (88, 13);
insert into user_teams (user_id, team_id) values (89, 14);
insert into user_teams (user_id, team_id) values (90, 15);
insert into user_teams (user_id, team_id) values (91, 16);
insert into user_teams (user_id, team_id) values (92, 17);
insert into user_teams (user_id, team_id) values (93, 18);
insert into user_teams (user_id, team_id) values (94, 19);
insert into user_teams (user_id, team_id) values (95, 20);
insert into user_teams (user_id, team_id) values (96, 21);
insert into user_teams (user_id, team_id) values (97, 22);
insert into user_teams (user_id, team_id) values (98, 23);
insert into user_teams (user_id, team_id) values (99, 24);
insert into user_teams (user_id, team_id) values (100, 25);
insert into user_teams (user_id, team_id) values (101, 26);
insert into user_teams (user_id, team_id) values (102, 27);
insert into user_teams (user_id, team_id) values (103, 28);
insert into user_teams (user_id, team_id) values (104, 29);
insert into user_teams (user_id, team_id) values (105, 30);
insert into user_teams (user_id, team_id) values (106, 31);
insert into user_teams (user_id, team_id) values (107, 32);
insert into user_teams (user_id, team_id) values (108, 33);
insert into user_teams (user_id, team_id) values (109, 34);
insert into user_teams (user_id, team_id) values (110, 35);
insert into user_teams (user_id, team_id) values (111, 36);
insert into user_teams (user_id, team_id) values (112, 37);
insert into user_teams (user_id, team_id) values (113, 38);
insert into user_teams (user_id, team_id) values (114, 39);
insert into user_teams (user_id, team_id) values (115, 40);
insert into user_teams (user_id, team_id) values (116, 41);
insert into user_teams (user_id, team_id) values (117, 42);
insert into user_teams (user_id, team_id) values (118, 43);
insert into user_teams (user_id, team_id) values (119, 44);
insert into user_teams (user_id, team_id) values (120, 45);
insert into user_teams (user_id, team_id) values (121, 46);
insert into user_teams (user_id, team_id) values (122, 47);
insert into user_teams (user_id, team_id) values (123, 48);
insert into user_teams (user_id, team_id) values (124, 49);
insert into user_teams (user_id, team_id) values (125, 50);
insert into user_teams (user_id, team_id) values (126, 51);
insert into user_teams (user_id, team_id) values (127, 52);
insert into user_teams (user_id, team_id) values (128, 53);
insert into user_teams (user_id, team_id) values (129, 54);
insert into user_teams (user_id, team_id) values (130, 55);
insert into user_teams (user_id, team_id) values (131, 56);
insert into user_teams (user_id, team_id) values (132, 57);
insert into user_teams (user_id, team_id) values (133, 58);
insert into user_teams (user_id, team_id) values (134, 59);
insert into user_teams (user_id, team_id) values (135, 60);
insert into user_teams (user_id, team_id) values (136, 61);
insert into user_teams (user_id, team_id) values (137, 62);
insert into user_teams (user_id, team_id) values (138, 63);
insert into user_teams (user_id, team_id) values (139, 64);
insert into user_teams (user_id, team_id) values (140, 65);
insert into user_teams (user_id, team_id) values (141, 66);
insert into user_teams (user_id, team_id) values (142, 67);
insert into user_teams (user_id, team_id) values (143, 68);
insert into user_teams (user_id, team_id) values (144, 69);
insert into user_teams (user_id, team_id) values (145, 70);
insert into user_teams (user_id, team_id) values (146, 71);
insert into user_teams (user_id, team_id) values (147, 72);
insert into user_teams (user_id, team_id) values (148, 73);
insert into user_teams (user_id, team_id) values (149, 74);
insert into user_teams (user_id, team_id) values (150, 75);
insert into user_teams (user_id, team_id) values (151, 1);
insert into user_teams (user_id, team_id) values (152, 2);
insert into user_teams (user_id, team_id) values (153, 3);
insert into user_teams (user_id, team_id) values (154, 4);
insert into user_teams (user_id, team_id) values (155, 5);
insert into user_teams (user_id, team_id) values (156, 6);
insert into user_teams (user_id, team_id) values (157, 7);
insert into user_teams (user_id, team_id) values (158, 8);
insert into user_teams (user_id, team_id) values (159, 9);
insert into user_teams (user_id, team_id) values (160, 10);
insert into user_teams (user_id, team_id) values (161, 11);
insert into user_teams (user_id, team_id) values (162, 12);
insert into user_teams (user_id, team_id) values (163, 13);
insert into user_teams (user_id, team_id) values (164, 14);
insert into user_teams (user_id, team_id) values (165, 15);
insert into user_teams (user_id, team_id) values (166, 16);
insert into user_teams (user_id, team_id) values (167, 17);
insert into user_teams (user_id, team_id) values (168, 18);
insert into user_teams (user_id, team_id) values (169, 19);
insert into user_teams (user_id, team_id) values (170, 20);
insert into user_teams (user_id, team_id) values (171, 21);
insert into user_teams (user_id, team_id) values (172, 22);
insert into user_teams (user_id, team_id) values (173, 23);
insert into user_teams (user_id, team_id) values (174, 24);
insert into user_teams (user_id, team_id) values (175, 25);
insert into user_teams (user_id, team_id) values (176, 26);
insert into user_teams (user_id, team_id) values (177, 27);
insert into user_teams (user_id, team_id) values (178, 28);
insert into user_teams (user_id, team_id) values (179, 29);
insert into user_teams (user_id, team_id) values (180, 30);
insert into user_teams (user_id, team_id) values (181, 31);
insert into user_teams (user_id, team_id) values (182, 32);
insert into user_teams (user_id, team_id) values (183, 33);
insert into user_teams (user_id, team_id) values (184, 34);
insert into user_teams (user_id, team_id) values (185, 35);
insert into user_teams (user_id, team_id) values (186, 36);
insert into user_teams (user_id, team_id) values (187, 37);
insert into user_teams (user_id, team_id) values (188, 38);
insert into user_teams (user_id, team_id) values (189, 39);
insert into user_teams (user_id, team_id) values (190, 40);
insert into user_teams (user_id, team_id) values (191, 41);
insert into user_teams (user_id, team_id) values (192, 42);
insert into user_teams (user_id, team_id) values (193, 43);
insert into user_teams (user_id, team_id) values (194, 44);
insert into user_teams (user_id, team_id) values (195, 45);
insert into user_teams (user_id, team_id) values (196, 46);
insert into user_teams (user_id, team_id) values (197, 47);
insert into user_teams (user_id, team_id) values (198, 48);
insert into user_teams (user_id, team_id) values (199, 49);
insert into user_teams (user_id, team_id) values (200, 50);
insert into user_teams (user_id, team_id) values (201, 51);
insert into user_teams (user_id, team_id) values (202, 52);
insert into user_teams (user_id, team_id) values (203, 53);
insert into user_teams (user_id, team_id) values (204, 54);
insert into user_teams (user_id, team_id) values (205, 55);
insert into user_teams (user_id, team_id) values (206, 56);
insert into user_teams (user_id, team_id) values (207, 57);
insert into user_teams (user_id, team_id) values (208, 58);
insert into user_teams (user_id, team_id) values (209, 59);
insert into user_teams (user_id, team_id) values (210, 60);
insert into user_teams (user_id, team_id) values (211, 61);
insert into user_teams (user_id, team_id) values (212, 62);
insert into user_teams (user_id, team_id) values (213, 63);
insert into user_teams (user_id, team_id) values (214, 64);
insert into user_teams (user_id, team_id) values (215, 65);
insert into user_teams (user_id, team_id) values (216, 66);
insert into user_teams (user_id, team_id) values (217, 67);
insert into user_teams (user_id, team_id) values (218, 68);
insert into user_teams (user_id, team_id) values (219, 69);
insert into user_teams (user_id, team_id) values (220, 70);
insert into user_teams (user_id, team_id) values (221, 71);
insert into user_teams (user_id, team_id) values (222, 72);
insert into user_teams (user_id, team_id) values (223, 73);
insert into user_teams (user_id, team_id) values (224, 74);
insert into user_teams (user_id, team_id) values (225, 75);
insert into user_teams (user_id, team_id) values (226, 1);
insert into user_teams (user_id, team_id) values (227, 2);
insert into user_teams (user_id, team_id) values (228, 3);
insert into user_teams (user_id, team_id) values (229, 4);
insert into user_teams (user_id, team_id) values (230, 5);
insert into user_teams (user_id, team_id) values (231, 6);
insert into user_teams (user_id, team_id) values (232, 7);
insert into user_teams (user_id, team_id) values (233, 8);
insert into user_teams (user_id, team_id) values (234, 9);
insert into user_teams (user_id, team_id) values (235, 10);
insert into user_teams (user_id, team_id) values (236, 11);
insert into user_teams (user_id, team_id) values (237, 12);
insert into user_teams (user_id, team_id) values (238, 13);
insert into user_teams (user_id, team_id) values (239, 14);
insert into user_teams (user_id, team_id) values (240, 15);
insert into user_teams (user_id, team_id) values (241, 16);
insert into user_teams (user_id, team_id) values (242, 17);
insert into user_teams (user_id, team_id) values (243, 18);
insert into user_teams (user_id, team_id) values (244, 19);
insert into user_teams (user_id, team_id) values (245, 20);
insert into user_teams (user_id, team_id) values (246, 21);
insert into user_teams (user_id, team_id) values (247, 22);
insert into user_teams (user_id, team_id) values (248, 23);
insert into user_teams (user_id, team_id) values (249, 24);
insert into user_teams (user_id, team_id) values (250, 25);
insert into user_teams (user_id, team_id) values (251, 26);
insert into user_teams (user_id, team_id) values (252, 27);
insert into user_teams (user_id, team_id) values (253, 28);
insert into user_teams (user_id, team_id) values (254, 29);
insert into user_teams (user_id, team_id) values (255, 30);
insert into user_teams (user_id, team_id) values (256, 31);
insert into user_teams (user_id, team_id) values (257, 32);
insert into user_teams (user_id, team_id) values (258, 33);
insert into user_teams (user_id, team_id) values (259, 34);
insert into user_teams (user_id, team_id) values (260, 35);
insert into user_teams (user_id, team_id) values (261, 36);
insert into user_teams (user_id, team_id) values (262, 37);
insert into user_teams (user_id, team_id) values (263, 38);
insert into user_teams (user_id, team_id) values (264, 39);
insert into user_teams (user_id, team_id) values (265, 40);
insert into user_teams (user_id, team_id) values (266, 41);
insert into user_teams (user_id, team_id) values (267, 42);
insert into user_teams (user_id, team_id) values (268, 43);
insert into user_teams (user_id, team_id) values (269, 44);
insert into user_teams (user_id, team_id) values (270, 45);
insert into user_teams (user_id, team_id) values (271, 46);
insert into user_teams (user_id, team_id) values (272, 47);
insert into user_teams (user_id, team_id) values (273, 48);
insert into user_teams (user_id, team_id) values (274, 49);
insert into user_teams (user_id, team_id) values (275, 50);
insert into user_teams (user_id, team_id) values (276, 51);
insert into user_teams (user_id, team_id) values (277, 52);
insert into user_teams (user_id, team_id) values (278, 53);
insert into user_teams (user_id, team_id) values (279, 54);
insert into user_teams (user_id, team_id) values (280, 55);
insert into user_teams (user_id, team_id) values (281, 56);
insert into user_teams (user_id, team_id) values (282, 57);
insert into user_teams (user_id, team_id) values (283, 58);
insert into user_teams (user_id, team_id) values (284, 59);
insert into user_teams (user_id, team_id) values (285, 60);
insert into user_teams (user_id, team_id) values (286, 61);
insert into user_teams (user_id, team_id) values (287, 62);
insert into user_teams (user_id, team_id) values (288, 63);
insert into user_teams (user_id, team_id) values (289, 64);
insert into user_teams (user_id, team_id) values (290, 65);
insert into user_teams (user_id, team_id) values (291, 66);
insert into user_teams (user_id, team_id) values (292, 67);
insert into user_teams (user_id, team_id) values (293, 68);
insert into user_teams (user_id, team_id) values (294, 69);
insert into user_teams (user_id, team_id) values (295, 70);
insert into user_teams (user_id, team_id) values (296, 71);
insert into user_teams (user_id, team_id) values (297, 72);
insert into user_teams (user_id, team_id) values (298, 73);
insert into user_teams (user_id, team_id) values (299, 74);
insert into user_teams (user_id, team_id) values (300, 75);

--rollback truncate table user_teams;