insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Canva Pro', 5, 1, 45);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Custom T-shirts', 3, 2, 46);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Udemy gift card', 3, 3, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Drawing tablet', 4, 4, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 5, 5, 49);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Office hours with investor', 5, 6, 50);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Premium hoodie', 1, 7, 51);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('E-book bundle', 1, 8, 52);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('LinkedIn Learning access', 4, 9, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Fitness tracker', 5, 10, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('AWS credits', 3, 11, 55);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 5, 12, 56);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Team trophy', 3, 13, 57);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Pluralsight access', 5, 14, 58);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 1, 15, 59);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 5, 16, 60);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Hackathon certificate', 1, 17, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup mentoring session', 5, 18, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Cloud credits', 2, 19, 63);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('3D printer', 1, 20, 64);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Canva Pro', 1, 1, 65);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 3, 2, 66);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Hackathon certificate', 1, 3, 67);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Year of Spotify Premium', 1, 4, 68);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Raspberry Pi kit', 3, 5, 69);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Adobe Creative Cloud subscription', 5, 6, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Mechanical keyboard', 1, 7, 71);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup mentoring session', 2, 8, 72);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Website hosting package', 4, 9, 73);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('VR headset', 5, 10, 74);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 4, 11, 75);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Hackathon certificate', 5, 12, 76);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Azure credits', 5, 13, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Medals', 2, 14, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Drone', 3, 15, 79);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Laptop stand', 3, 16, 80);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Trello Gold', 4, 17, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Azure credits', 4, 18, 82);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 5, 19, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('VR headset', 4, 20, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 4, 1, 85);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('GitHub Pro', 2, 2, 86);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('3D printer', 4, 3, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Raspberry Pi kit', 5, 4, 88);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Trello Gold', 3, 5, 89);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Cloud credits', 2, 6, 90);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Apple Watch', 4, 7, 91);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('LinkedIn Learning access', 5, 8, 92);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Smart home device', 3, 9, 93);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Gaming mouse', 3, 10, 94);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Cash prize', 4, 11, 95);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Custom swag box', 1, 12, 96);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Udemy gift card', 1, 13, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('External SSD', 4, 14, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Ergonomic chair', 3, 15, 99);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 5, 16, 100);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Smartwatch', 3, 17, 101);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Arduino starter kit', 2, 18, 102);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Year of Notion Pro', 1, 19, 103);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Azure credits', 3, 20, 104);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('GitHub Pro', 2, 1, 105);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Premium hoodie', 2, 2, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 3, 3, 107);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 1, 4, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Coursera Plus subscription', 3, 5, 109);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Trello Gold', 1, 6, 110);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('LinkedIn Learning access', 3, 7, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 5, 8, 112);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Drone', 1, 9, 113);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Mechanical keyboard', 2, 10, null);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Bluetooth speakers', 3, 11, 115);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 1, 12, 116);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup mentoring session', 1, 13, 117);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Gaming mouse', 2, 14, 118);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 2, 15, 119);

--rollback truncate table prizes;