insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Canva Pro', 5, 1, 1);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Custom T-shirts', 3, 2, 2);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Udemy gift card', 3, 3, 3);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Drawing tablet', 4, 4, 4);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 5, 5, 5);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Office hours with investor', 5, 6, 6);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Premium hoodie', 1, 7, 7);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('E-book bundle', 1, 8, 8);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('LinkedIn Learning access', 4, 9, 9);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Fitness tracker', 5, 10, 10);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('AWS credits', 3, 11, 11);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 5, 12, 12);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Team trophy', 3, 13, 13);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Pluralsight access', 5, 14, 14);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 1, 15, 15);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 5, 16, 16);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Hackathon certificate', 1, 17, 17);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup mentoring session', 5, 18, 18);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Cloud credits', 2, 19, 19);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('3D printer', 1, 20, 20);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Canva Pro', 1, 1, 21);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 3, 2, 22);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Hackathon certificate', 1, 3, 23);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Year of Spotify Premium', 1, 4, 24);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Raspberry Pi kit', 3, 5, 25);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Adobe Creative Cloud subscription', 5, 6, 26);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Mechanical keyboard', 1, 7, 27);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup mentoring session', 2, 8, 28);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Website hosting package', 4, 9, 29);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('VR headset', 5, 10, 30);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 4, 11, 31);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Azure credits', 5, 13, 32);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Medals', 2, 14, 33);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Drone', 3, 15, 34);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Laptop stand', 3, 16, 35);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Trello Gold', 4, 17, 36);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Azure credits', 4, 18, 37);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 5, 19, 38);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('VR headset', 4, 20, 39);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 4, 1, 40);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('GitHub Pro', 2, 2, 41);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('3D printer', 4, 3, 42);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Raspberry Pi kit', 5, 4, 43);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Trello Gold', 3, 5, 44);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Cloud credits', 2, 6, 45);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Apple Watch', 4, 7, 46);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('LinkedIn Learning access', 5, 8, 47);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Smart home device', 3, 9, 48);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Gaming mouse', 3, 10, 49);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Cash prize', 4, 11, 50);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Custom swag box', 1, 12, 51);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Udemy gift card', 1, 13, 52);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('External SSD', 4, 14, 53);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Ergonomic chair', 3, 15, 54);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 5, 16, 55);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Smartwatch', 3, 17, 56);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Arduino starter kit', 2, 18, 57);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Year of Notion Pro', 1, 19, 58);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Azure credits', 3, 20, 59);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('GitHub Pro', 2, 1, 60);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Premium hoodie', 2, 2, 61);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 3, 3, 62);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Kindle Paperwhite', 1, 4, 63);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Coursera Plus subscription', 3, 5, 64);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Trello Gold', 1, 6, 65);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('LinkedIn Learning access', 3, 7, 66);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup legal consultation', 5, 8, 67);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Drone', 1, 9, 68);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Mechanical keyboard', 2, 10, 69);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Bluetooth speakers', 3, 11, 70);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 1, 12, 71);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Startup mentoring session', 1, 13, 72);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Gaming mouse', 2, 14, 73);
insert into prizes (name, quantity, hackathon_id, team_hackathon_id) values ('Visa prepaid card', 2, 15, 74);

--rollback truncate table prizes;